In [1]:
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Query local DataFrames with SQL

https://www.ers.usda.gov/data-products/wheat-data

In [2]:
%pip install python-calamine pandas bigframes

Requirement already satisfied: python-calamine in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (0.6.2)
Requirement already satisfied: pandas in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: bigframes in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (2.39.0)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: cloudpickle>=2.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (3.1.2)
Requirement already satisfied: fsspec>=2023.3.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2026.1.0)
Requirement already satisfied: gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2026.1.0)
Requirement already satisfied: geopandas>=0.12.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.1.3)
Requirement already satisfied: google-auth<3.0,>=2.15.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2.49.1)
Requirement already satisfied: google-cloud-bigquery>=3.36.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-cloud-bigquery[bqstorage,pandas]>=3.36.0->bigframes) (3.41.0)
Requirement already satisfied: google-cloud-bigquery-storage<3.0.0,>=2.30.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2.37.0)
Requirement already satisfied: google-cloud-functions>=1.12.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.23.0)
Requirement already satisfied: google-cloud-bigquery-connection>=1.12.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.21.0)
Requirement already satisfied: google-cloud-resource-manager>=1.10.3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.17.0)
Requirement already satisfied: google-cloud-storage>=2.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (3.10.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.8.0)
Requirement already satisfied: grpc-google-iam-v1>=0.14.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (0.14.4)
Requirement already satisfied: pandas-gbq>=0.26.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (0.34.1)
Requirement already satisfied: pyarrow>=15.0.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (23.0.1)
Requirement already satisfied: pydata-google-auth>=1.8.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.9.1)
Requirement already satisfied: requests>=2.27.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2.33.1)
Requirement already satisfied: shapely>=1.8.5 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2.1.2)
Requirement already satisfied: tabulate>=0.9 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (0.10.0)
Requirement already satisfied: humanize>=4.6.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (4.15.0)
Requirement already satisfied: matplotlib>=3.7.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (3.10.8)
Requirement already satisfied: db-dtypes>=1.4.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.5.1)
Requirement already satisfied: pyiceberg>=0.7.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (0.11.1)
Requirement already satisfied: atpublic<6,>=2.3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (5.1)
Requirement already satisfied: pytz>=2022.7 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (2026.1.post1)
Requirement already satisfied: toolz<2,>=0.11 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (1.1.0)
Requirement already satisfied: typing-extensions<5,>=4.5.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (4.15.0)
Requirement already satisfied: rich<14,>=12.4.4 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from bigframes) (13.9.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-auth<3.0,>=2.15.0->bigframes) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-auth<3.0,>=2.15.0->bigframes) (46.0.6)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-bigquery-storage<3.0.0,>=2.30.0->bigframes) (2.30.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-cloud-bigquery-storage<3.0.0,>=2.30.0->bigframes) (1.80.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-cloud-bigquery-storage<3.0.0,>=2.30.0->bigframes) (1.27.2)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-cloud-bigquery-storage<3.0.0,>=2.30.0->bigframes) (6.33.6)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-api-core<3.0.0,>=2.11.0->google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-bigquery-storage<3.0.0,>=2.30.0->bigframes) (1.74.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-bigquery-storage<3.0.0,>=2.30.0->bigframes) (1.80.0)
Requirement already satisfied: six>=1.5 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from requests>=2.27.1->bigframes) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from requests>=2.27.1->bigframes) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from requests>=2.27.1->bigframes) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from requests>=2.27.1->bigframes) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from rich<14,>=12.4.4->bigframes) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from rich<14,>=12.4.4->bigframes) (2.20.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from cryptography>=38.0.3->google-auth<3.0,>=2.15.0->bigframes) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0,>=2.15.0->bigframes) (3.0)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from db-dtypes>=1.4.2->bigframes) (26.0)
WARNING: Cache entry deserialization failed, entry ignored
Collecting pandas
  Using cached pandas-2.3.3-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pandas) (2026.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (3.13.5)
Requirement already satisfied: decorator>4.1.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (5.2.1)
Requirement already satisfied: google-auth-oauthlib in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (1.3.1)
Requirement already satisfied: google-cloud-storage-control in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (1.11.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (1.23.0)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from geopandas>=0.12.2->bigframes) (0.12.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from geopandas>=0.12.2->bigframes) (3.7.2)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-cloud-bigquery>=3.36.0->google-cloud-bigquery[bqstorage,pandas]>=3.36.0->bigframes) (2.5.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-cloud-bigquery>=3.36.0->google-cloud-bigquery[bqstorage,pandas]>=3.36.0->bigframes) (2.8.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich<14,>=12.4.4->bigframes) (0.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from matplotlib>=3.7.1->bigframes) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from matplotlib>=3.7.1->bigframes) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from matplotlib>=3.7.1->bigframes) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from matplotlib>=3.7.1->bigframes) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from matplotlib>=3.7.1->bigframes) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from matplotlib>=3.7.1->bigframes) (3.3.2)
Requirement already satisfied: setuptools in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pandas-gbq>=0.26.1->bigframes) (82.0.1)
Requirement already satisfied: psutil>=5.9.8 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pandas-gbq>=0.26.1->bigframes) (7.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from google-auth-oauthlib->gcsfs!=2025.5.0,!=2026.2.0,!=2026.3.0,>=2023.3.0->bigframes) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0,>=2.15.0->bigframes) (0.6.3)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyiceberg>=0.7.1->bigframes) (5.2.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyiceberg>=0.7.1->bigframes) (8.3.2)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyiceberg>=0.7.1->bigframes) (1.7.3)
Requirement already satisfied: pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyiceberg>=0.7.1->bigframes) (2.12.5)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyiceberg>=0.7.1->bigframes) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (from pyiceberg>=0.7.1->bigframes) (1.0.4)

In [3]:
!wget -O /tmp/wheat-data.xlsx 'https://www.ers.usda.gov/media/5706/wheat-data-all-years.xlsx?v=19753'

--2026-05-07 17:55:50--  https://www.ers.usda.gov/media/5706/wheat-data-all-years.xlsx?v=19753
Resolving www.ers.usda.gov (www.ers.usda.gov)... 20.141.137.224
Connecting to www.ers.usda.gov (www.ers.usda.gov)|20.141.137.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 814596 (796K) [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet]
Saving to: ‘/tmp/wheat-data.xlsx’

/tmp/wheat-data.xls 100%[===================>] 795.50K  2.32MB/s    in 0.3s

2026-05-07 17:55:51 (2.32 MB/s) - ‘/tmp/wheat-data.xlsx’ saved [814596/814596]

In [4]:
import pandas as pd

df = pd.read_excel(
    "/tmp/wheat-data.xlsx",
    sheet_name="Table06",
    header=1,

    # Requires that the python-calamine project is also installed.
    engine="calamine",

    # Recommended so that string columns don't contain NaN, which can confuse
    # parquet serialization, which we use to read these data in BigQuery SQL.
    dtype_backend="pyarrow",
)
df

,Marketing year 1/,Type 2/,Beginning stocks,Production,Imports,Total supply 3/ 4/,Food use,Seed use,Feed and residual use,Total domestic use 4/,Exports,Total disappearance 4/,Ending stocks
0,1950/51,All wheat,496.0,1019.0,11,1526.0,580.0,--,109.0,689.0,345.0,1034.0,492.0
1,1951/52,All wheat,492.0,988.0,30,1510.0,585.0,--,110.0,695.0,485.0,1180.0,330.0
2,1952/53,All wheat,330.0,1306.0,24,1660.0,578.0,--,78.0,656.0,332.0,988.0,672.0
3,1953/54,All wheat,672.0,1173.0,6,1851.0,556.0,--,87.0,643.0,214.0,857.0,994.0
4,1954/55,All wheat,994.0,984.0,3,1981.0,552.0,--,53.0,605.0,267.0,872.0,1109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,"2/ Hard Red Winter, Hard Red Spring, Soft Red ...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
288,3/ Includes flour and selected other products ...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
289,4/ Totals may not add due to rounding.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
290,"Source: USDA, Economic Research Service, based...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
291,"Updated: April 10, 2026",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [5]:
# To aid in SQL authoring, rename the columns to avoid problematic special
# characters.  Note: BigQuery supports some special characters, but not "/".
# https://docs.cloud.google.com/bigquery/docs/schemas#flexible-column-names
df_renamed = df.rename(
    columns={
        column: column.replace("/", "")
        for column in df.columns
    }
)

# Also, give a name to the index so that it can be included.
df_renamed.index.name = "rowindex"
df_renamed

,Marketing year 1,Type 2,Beginning stocks,Production,Imports,Total supply 3 4,Food use,Seed use,Feed and residual use,Total domestic use 4,Exports,Total disappearance 4,Ending stocks
rowindex,,,,,,,,,,,,,
0,1950/51,All wheat,496.0,1019.0,11,1526.0,580.0,--,109.0,689.0,345.0,1034.0,492.0
1,1951/52,All wheat,492.0,988.0,30,1510.0,585.0,--,110.0,695.0,485.0,1180.0,330.0
2,1952/53,All wheat,330.0,1306.0,24,1660.0,578.0,--,78.0,656.0,332.0,988.0,672.0
3,1953/54,All wheat,672.0,1173.0,6,1851.0,556.0,--,87.0,643.0,214.0,857.0,994.0
4,1954/55,All wheat,994.0,984.0,3,1981.0,552.0,--,53.0,605.0,267.0,872.0,1109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,"2/ Hard Red Winter, Hard Red Spring, Soft Red ...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
288,3/ Includes flour and selected other products ...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
289,4/ Totals may not add due to rounding.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
290,"Source: USDA, Economic Research Service, based...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
291,"Updated: April 10, 2026",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [6]:
import bigframes.pandas as bpd

# TODO(developer): Follow the instructions at
# https://docs.cloud.google.com/bigquery/docs/sandbox and set the project to the
# ID of the project you created.
bpd.options.bigquery.project = "swena-bq-sandbox"

In [7]:
%%bqsql df_with_year
SELECT
  REGEXP_EXTRACT(LTRIM(`Marketing year 1`), r'^([0-9]+)/[0-9]') AS `Start year`,
  SAFE_CAST(`Seed use` AS FLOAT64) AS `Seed use`,
  * EXCEPT (`Marketing year 1`, `Seed use`)
FROM {df_renamed}
ORDER BY rowindex ASC

UsageError: Cell magic `%%bqsql` not found.

In [ ]:
%%bqsql use_proportions
SELECT
  `rowindex`,
  `Start year`,
  `Seed use` / `Total disappearance 4` AS `Seed proportion`,
  `Food use` / `Total disappearance 4` AS `Food proportion`,
  `Feed and residual use` / `Total disappearance 4` AS `Feed proportion`,
  `Exports` / `Total disappearance 4` AS `Exports proportion`
FROM {df_with_year}
WHERE TRIM(`Type 2`) = 'All wheat'
ORDER BY `rowindex` ASC;

In [ ]:
use_proportions.set_index('Start year')[['Seed proportion', 'Food proportion', 'Feed proportion', 'Exports proportion']].plot.area(stacked=True, ylim=(0, 1.5), colormap='viridis')

In [ ]:
type(use_proportions)

In [ ]:
pandas_result = use_proportions.to_pandas()
pandas_result